---
ttn:
  mqtt_url: "tcp://eu1.cloud.thethings.network"
  identity_server_url: "https://eu1.cloud.thethings.network"
  identity_server_timeout: 20
  apps:
  - name: "ttn-application-name"
    key: "ttn-api-key"
    encoding: "JSON"
json:
  - path: "/humidity"
    item: "HUMI"
  - path: "/temperature"
    item: "TEMP"
  - path: "/pm10"
    item: "PM10"
  - path: "/pm2_5"
    item: "PM2_5"
senscom:
  url: "https://api.sensor.community"
  timeout: 30
opensense:
  url: "https://api.opensensemap.org"
  timeout: 30
mydevices:
  url: "https://api.mydevices.com"
  timeout: 30

